#spring.application.name=demo
#spring.jpa.database=PostgresSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/susong-app
#spring.datasource.username=postgres
#spring.datasource.password=Pg123456
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.address=192.168.56.1
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/App_1 
spring.datasource.username=postgres
spring.datasource.password=Pg123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true